checks:
    javascript: true
filter:
    excluded_paths:
        - test/*
build:
    environment:
        node: '8.4.0'
    tests:
        override:
            -
                command: './node_modules/.bin/istanbul cover --report clover test.js'
                coverage:
                    file: 'test/unit/coverage/clover.xml'
                    format: 'clover'
