checks:
    javascript: true
filter:
    excluded_paths:
        - test/*
build:
    environment:
        node: '8.4.0'
    tests:
        override:
            -
                command: './node_modules/.bin/jest --config ./build/jest.config.coverage.js --report clover'
                coverage:
                    file: './test/unit/coverage/clover.xml'
                    format: 'clover'
