checks:
    javascript: true
filter:
    excluded_paths:
        - test/*
build:
    environment:
        node: '8.5.0'
    project_setup:
        before:
            - npm install yarn -g
    tests:
        override:
            -
                command: 'yarn install'
            -
                command: 'yarn run test:coverage'
                coverage:
                    file: './test/unit/coverage/clover.xml'
                    format: 'clover'
