checks:
    javascript: true
filter:
    excluded_paths:
        - test/*
        - node_modules/*
        - build/*
        - dist/*
build:
    environment:
        node: '8.9.4'
    tests:
        override:
            -
                command: 'yarn run test:coverage'
                coverage:
                    file: './test/unit/coverage/clover.xml'
                    format: 'clover'
