checks:
    javascript: true
filter:
    excluded_paths:
        - test/*
build:
    environment:
        node: '8.4.0'
    tests:
        override:
            -
                command: 'npm run test:coverage'
                coverage:
                    file: './test/unit/coverage/clover.xml'
                    format: 'clover'
